import {
    AlertTriangle,
    ArrowRight,
    Check,
    ChevronLeft,
    ChevronRight,
    Clipboard,
    Command,
    Copy,
    CreditCard,
    File,
    FileText,
    HelpCircle,
    Image,
    Laptop,
    Loader2,
    Moon,
    MoreVertical,
    Pizza,
    Plus,
    Settings,
    Sun,
    Trash,
    Twitter,
    User,
    X,
    Menu,
    Compass,
    Wrench,
    MessageSquare,
    FolderOpen,
    Home,
    Package,
    Bot,
    Send,
    StopCircle,
    RefreshCw,
    Download,
    Code,
    Cpu,
    Zap,
    Key,
    LogOut,
    Mail,
    Lock,
    Eye,
    EyeOff,
    Sparkles,
    Search,
    ChevronDown,
    ExternalLink,
    Globe,
    Upload,
    Code2,
    Braces,
    Settings2,
    ScrollText,
    Inbox,
    Rocket,
    Users,
    StickyNote,
    Maximize2,
    CircleHelp,
    RotateCcw,
    CornerDownLeft,
    LogIn,
    AlertCircle,
    Pencil,
    Scroll,
    CheckCircle2,
    Info,
    UserCheck,
    BadgeCheck,
    BookOpen,
    Github,
    Gauge,
    Palette,
    Share2,
    Heart,
    GitFork,
  
  } from 'lucide-react';
  

  
  export const Icons = {
    logo: Command,
    logoSimple: Bot,
    close: X,
    spinner: Loader2,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    chevronDown: ChevronDown,
    trash: Trash,
    post: FileText,
    page: File,
    media: Image,
    settings: Settings,
    billing: CreditCard,
    ellipsis: MoreVertical,
    add: Plus,
    warning: AlertTriangle,
    user: User,
    arrowRight: ArrowRight,
    help: HelpCircle,
    pizza: Pizza,
    sun: Sun,
    moon: Moon,
    laptop: Laptop,
    twitter: Twitter,
    check: Check,
    copy: Copy,
    clipboard: Clipboard,
    menu: Menu,
    compass: Compass,
    tool: Wrench,
    chat: MessageSquare,
    project: FolderOpen,
    home: Home,
    package: Package,
    agent: Bot,
    send: Send,
    stop: StopCircle,
    refresh: RefreshCw,
    download: Download,
    code: Code,
    cpu: Cpu,
    zap: Zap,
    key: Key,
    logout: LogOut,
    mail: Mail,
    lock: Lock,
    eye: Eye,
    eyeOff: EyeOff,
    sparkles: Sparkles,
    search: Search,
    image: Image,
    externalLink: ExternalLink,
    globe: Globe,
    upload: Upload,
    python: Code2,
    braces: Braces,
    config: Settings2,
    logs: ScrollText,
    inbox: Inbox,
    rocket: Rocket,
    robot: Bot,
    group: Users,
    note: StickyNote,
    resize: Maximize2,
    deepseek: Sparkles,
    question: CircleHelp,
    reset: RotateCcw,
    enter: CornerDownLeft,
    exit: LogIn,
    alert: AlertCircle,
    edit: Pencil,
    scroll: Scroll,
    checkCircle: CheckCircle2,
    info: Info,
    userVoiceFill: UserCheck,
    badgeCheck: BadgeCheck,
    docs: BookOpen,
    github: Github,
    circleGauge: Gauge,
    theme: Palette,
    share: Share2,
    heart: Heart,
    gitFork: GitFork,
  };
  
  